plot(powcon$datetime, powcon$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
lines(powcon$datetime , powcon$Sub_metering_1)
lines(powcon$datetime , powcon$Sub_metering_2,  col = "red")
lines(powcon$datetime , powcon$Sub_metering_3,  col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = 1)
dev.copy(png, file = "plot3.png", width = 480, height = 480, units = "px")
dev.off()