par(mfrow = c(2,2),mar = c(5,4,2,1))
with(powcon,{
  plot(datetime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
  plot(datetime, Voltage, type = "l")
  plot(datetime, Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
  lines(datetime , Sub_metering_1)
  lines(datetime , Sub_metering_2,  col = "red")
  lines(datetime , Sub_metering_3,  col = "blue")
  legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = 1, bty = "n")
  plot(datetime, Global_reactive_power, type = "l")
})
dev.copy(png, file = "plot4.png", width = 480, height = 480, units = "px")
dev.off()